### ISSUE TITLE
How to getAllClass from sourcefile

### ISSUE THREAD

**Issue by WanderWang** [wessberg/CodeAnalyzer#19]
I need a method to found out all class such as 

```
const classSet = classService.getAllClass( aSourceFile )
```

have any solution ?

**Comment by wessberg** [comment]
For all services there are getAll() and getAllForFile() methods.

So, you just call

classService.getAll(sourcefile).

You can also provide a second argument, deep, if you want it to look for nested anonymous classes inside expressions. 😊

**Comment by WanderWang** [comment]
my mistake ,sorry
