### ISSUE TITLE
crash on class.toLightAST();

### ISSUE THREAD

**Issue by WanderWang** [wessberg/CodeAnalyzer#21]
here is the test code :  

```
class MyClass {

    method() {

    };   //here is a semicolon
}
```

myClass.toLightAST()  throw ``` TypeError: Could not map a node of kind: "SemicolonClassElement" to a ClassElementCtor ```

**Comment by WanderWang** [comment]
Anything update ?

**Comment by WanderWang** [comment]
@wessberg

**Comment by wessberg** [comment]
Hi. Sorry, I have been busy. I’ll get around to it soon.

**Comment by wessberg** [comment]
This has been fixed in the latest version.
